### ISSUE TITLE
what do these two symbols mean？ "test_nc_accuracy" and "train_nc_accuracy"    

### ISSUE THREAD

**Issue by xixihahalsr** [pilancilab/scnn_experiments#1]
Dear authors, 
what do these two symbols mean？ "test_nc_accuracy" and "train_nc_accuracy"       Also, what is the  different between "test_nc_accuracy" and "test_accuracy" ?

**Comment by aaronpmishkin** [comment]
Thanks for your question. The `test_nc_accuracy` metric is the test accuracy of the prediction model in the non-convex parameterization, while `test_accuracy` is the test accuracy in the convex parameterization. These need not be the same.
